import = [
   "~/.config/alacritty/themes/tokyo-night.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 150, lines = 50 }
padding = { x = 5, y = 5 }
position = { x = 20, y = 110}
decorations = "Buttonless"
opacity = 0.9
blur = true
option_as_alt = "Both"

[font]
normal = { family = "GoMono Nerd Font Mono", style = "Regular" }
size = 14

[[keyboard.bindings]]
# tmux : create new window 
key = "T"
mods = "Command"
chars = "\u0000c"






