import = [
   "~/.config/alacritty/themes/tokyo-night.toml"
]

[window]
dimensions = { columns = 145, lines = 42 }
padding = { x = 10, y = 30 }
position = { x = 30, y = 80}
decorations = "Transparent"
opacity = 0.4
blur = true

[font]
normal = { family = "GoMono Nerd Font", style = "Regular" }
size = 17

[[keyboard.bindings]]
# tmux : create new window 
key = "T"
mods = "Command"
chars = "\u0000c"

[[keyboard.bindings]]
# tmux : open tmux session manager popup 
key = "A"
mods = "Command"
chars = "\u0000K"

[env]
TERM = "xterm-256color"





