import = [
   "~/.config/alacritty/themes/catppuccin-mocha.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
]

[window]
dimensions = { columns = 140, lines = 40 }
padding = { x = 10, y = 30 }
position = { x = 150, y = 200}
decorations = "Transparent"
opacity = 0.7
blur = true

[font]
normal = { family = "GoMono Nerd Font", style = "Regular" }
size = 15

[env]
TERM = "xterm-256color"



