require("customs.keymaps")
local s = require("utils").source_plugin

s("lsp")
s("lspsaga")
s("lsp-kind")
-- s('themer')
s("cd-project")
s("luasnip")
s("cmp")
s("cmp-sources")
s("mason-config")
s("fugitive")
s("treesitter")
s("noice")
s("notify")
s("alpha")
s("harpoon")
s("oil")
s("nvim-ts-autotag")
s("telescope")
s("neoscroll")
s("null-ls")
s("prettier")
s("comment")
s("formatter")
-- s("nvim-spider")
s("indent-blankline")
s("lualine")
s("barbecue")
s("leetcode")
s("flash")
s("rnvimr")
s("obsidian")
-- s('smooth-cursor')
s("pomo")
s("trouble")
-- s('fidget')
-- s('incline')
-- s('hydrate')
s("typescript-tools")
-- s('flutter-tools')
-- s('gitsigns')

-- colorschemes
-- s('themery')
