#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

$HOME/.config/yabai/create_spaces.sh

yabai -m config external_bar               all:0:40     \
                window_border              off           \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.15         \
                active_window_opacity      1.0          \
                normal_window_opacity      1.0         \
                window_border_width        2            \
                window_border_hidpi        off          \
                window_border_radius       11           \
                window_animation_duration  0.22         \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff2a2f38   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               on          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                8           \
                bottom_padding             8           \
                left_padding               5           \
                right_padding              5           \
                window_gap                 8

yabai -m rule --add label="Finder" app="^Finder$" manage=off 
yabai -m rule --add label="Simulator" app="^Simulator$" manage=on 
yabai -m rule --add label="Messages" app="^Messages$" manage=off
yabai -m rule --add label="Font Book" app="^Font Book$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Logi Options+" app="Logi Options+" manage=off
yabai -m rule --add label="Karabiner-Elements" app="Karabiner-Elements" manage=off
yabai -m rule --add label="Pika" app="Pika" manage=off
yabai -m rule --add label="Steam" app="Steam" manage=off
# yabai -m rule --add app="^Live Wallaper$" manage=off

yabai -m config layout bsp

echo "yabai configuration loaded.."

