require('plugins.' .. 'keymaps')

require('plugins.' .. 'configs.' .. 'cmp')
require('plugins.' .. 'configs.' .. 'cmp-sources')
require('plugins.' .. 'configs.' .. 'lsp')
require('plugins.' .. 'configs.' .. 'lsp-inlayhints')
require('plugins.' .. 'configs.' .. 'mason-config')
require('plugins.' .. 'configs.' .. 'fugitive')
require('plugins.' .. 'configs.' .. 'treesitter')
require('plugins.' .. 'configs.' .. 'trouble')
-- require('plugins.' .. 'configs.' .. 'noice')
require('plugins.' .. 'configs.' .. 'lspsaga')
require('plugins.' .. 'configs.' .. 'notify')
require('plugins.' .. 'configs.' .. 'alpha')
require('plugins.' .. 'configs.' .. 'flutter-tools')
require('plugins.' .. 'configs.' .. 'gitsigns')
require('plugins.' .. 'configs.' .. 'harpoon')
require('plugins.' .. 'configs.' .. 'oil')
require('plugins.' .. 'configs.' .. 'telescope')
require('plugins.' .. 'configs.' .. 'neoscroll')
require('plugins.' .. 'configs.' .. 'fidget')
require('plugins.' .. 'configs.' .. 'null-ls')
require('plugins.' .. 'configs.' .. 'prettier')
require('plugins.' .. 'configs.' .. 'comment')
require('plugins.' .. 'configs.' .. 'formatter')
require('plugins.' .. 'configs.' .. 'nvim-spider')
require('plugins.' .. 'configs.' .. 'indent-blankline')
require('plugins.' .. 'configs.' .. 'lualine')
require('plugins.' .. 'configs.' .. 'barbecue')
require('plugins.' .. 'configs.' .. 'leetcode')
require('plugins.' .. 'configs.' .. 'themery')
require('plugins.' .. 'configs.' .. 'material')
require('plugins.' .. 'configs.' .. 'tokyonight')
require('plugins.' .. 'configs.' .. 'night-owl')
require('plugins.' .. 'configs.' .. 'flash')
