require 'plugins.keymaps'
local CONF = 'plugins.configs.'

require(CONF .. 'cmp')
require(CONF .. 'cmp-sources')
require(CONF .. 'lsp')
require(CONF .. 'lsp-inlayhints')
require(CONF .. 'mason-config')
require(CONF .. 'fugitive')
require(CONF .. 'treesitter')
require(CONF .. 'trouble')
require(CONF .. 'noice')
require(CONF .. 'notify')
require(CONF .. 'alpha')
require(CONF .. 'flutter-tools')
require(CONF .. 'gitsigns')
require(CONF .. 'harpoon')
require(CONF .. 'oil')
require(CONF .. 'telescope')
require(CONF .. 'neoscroll')
require(CONF .. 'fidget')
require(CONF .. 'null-ls')
require(CONF .. 'prettier')
require(CONF .. 'comment')
require(CONF .. 'formatter')
require(CONF .. 'nvim-spider')
require(CONF .. 'indent-blankline')
require(CONF .. 'lualine')
require(CONF .. 'barbecue')
require(CONF .. 'leetcode')
require(CONF .. 'themery')
require(CONF .. 'material')
require(CONF .. 'tokyonight')
require(CONF .. 'night-owl')
