require("conform").setup({
    -- formatters_by_ft = {
    --     lua = { "stylua" },
    --     -- Conform will run multiple formatters sequentially
    --     python = { "isort", "black" },
    --     -- Use a sub-list to run only the first available formatter
    --     javascript = { { "prettierd", "prettier" } },
    --     dart = { "dartfmt" }
    -- },
    -- formatters = {
    --     dartfmt = {
    --         command = "/Users/thanhhoann/flutter/bin/dart",
    --         args = { "--format", "$FILENAME" },
    --     }
    -- },
    -- format_on_save = {
    --     -- I recommend these options. See :help conform.format for details.
    --     lsp_fallback = true,
    --     timeout_ms = 500,
    -- },
    -- notify_on_error = true,
})
